### ISSUE TITLE
Installation problem in MacOS 

### ISSUE THREAD

**Issue by mishugeb** [kgori/sigfit#46]
**Tried to install in my MacOS R 3.6.0 but ended up with the following error.** 

18 warnings and 19 errors generated.
   make: *** [Modules.o] Error 1
   ERROR: compilation failed for package ‘sigfit’
─  removing ‘/private/var/folders/2y/pcfyrybs5bj6wr_qdndq4vnr0000gp/T/RtmpV709Md/Rinst940518763ba0/sigfit’
         -----------------------------------
   ERROR: package installation failed
Error: Failed to install 'sigfit' from GitHub:
  System command error, exit status: 1, stderr empty

**Comment by kgori** [comment]
Hi,

Sorry to hear you're having trouble installing sigfit.

It's hard to know exactly what the problem is from your error message as it looks like that is just the last few lines of a more detailed error report. However, I think it will be related to two issues that I know about, that I am working on fixing.

The issues are:

1. rstan and StanHeaders have updated and now need to use c++14, but sigfit is set up to use c++11
2. R 3.6.0 now disallows certain hard coded file paths within packages (staged installs), and sigfit still has these in the structure of the package in order to make stan work.

In the meantime, the following workaround should help you get sigfit installed. It's a bit less convenient, compared to using devtools, but it's not too difficult.

In a terminal, do:

    git clone https://github.com/kgori/sigfit.git
    cd sigfit

Then edit the file `src/Makevars` and change the first line to:

    CXX_STD = CXX14

Then launch R from the terminal in the sigfit directory, and run:

    pkgbuild::compile_dll(path = ".")
    devtools::document(pkg = ".")
    devtools::install(pkg = ".", args = "--no-staged-install", upgrade = "never", build_vignettes = FALSE, quick = TRUE)
    
Optionally follow up with these commands, if the vignettes are missing:

    devtools::build_vignettes(pkg = ".", install = FALSE)
    devtools::install(pkg = ".", args = "--no-staged-install", upgrade = "never", build_vignettes = FALSE, quick = TRUE)

Once  sigfit is installed, you can delete the git repository.

**Comment by mishugeb** [comment]
Thanks, the installation worked perfect. I couldn't open the vignettes though. But I can get the instructions from the website: http://htmlpreview.github.io/?https://github.com/kgori/sigfit/blob/master/inst/doc/sigfit_vignette.html

**Comment by kgori** [comment]
Good, glad that worked for you. There will be a permanent fix in the next release.
