### ISSUE TITLE
Can't find vignette

### ISSUE THREAD

**Issue by Dagsbio** [kgori/sigfit#50]
Hi,

As of today, I can't find the vignette neither via **browseVignettes("sigfit")** nor **http://htmlpreview.github.io/?https://github.com/kgori/sigfit/blob/master/inst/doc/sigfit_vignette.html**

**Comment by baezortega** [comment]
Hi David,

It seems that the HTML vignette disappeared from GitHub at some point. You can try building the vignette locally using `tools::buildVignettes("sigfit")`. If you are successful, then you should be able to open it using `browseVignettes("sigfit") `.

This issue will be solved with the release of sigfit v2.0, which is planned for this Friday. However, there are some changes to the package functions in the new version, so you would need to install the new version (once it's out) before trying to follow the new vignette.

Best,
Adrian

**Comment by Dagsbio** [comment]
Thanks, the workaround did not work, but I surely can wait till friday :)

David.

**Comment by baezortega** [comment]
Hi David,

Just out of curiosity, could you check if this works for you?

`tools::buildVignettes("sigfit", find.package("sigfit"))`

Thanks,
Adrian

__Edit: I think this only works if the vignette is already installed. I found a way of building it locally, which will be included in the README for v2.0__

**Comment by Dagsbio** [comment]
Hi Adrian,

Yep, that didn't work either so the problem might be the one you are mentioning. 

Let me know if I can try anything else to help.

Cheers,

David.

**Comment by baezortega** [comment]
Hi David,

The new version of the package is already out on GitHub:
https://github.com/kgori/sigfit.

The installation command has changed; I would recommend you to uninstall
the version you have before installing the new one. Because the new version
of Stan depends on C++14 rather than C++11, you might run into some issues.
Let me know how it works.

Best,
Adrian
On 8 Nov 2019 09:49, "David Gómez" <notifications@github.com> wrote:

Hi Adrian,

Yep, that didn't work either so the problem might be the one you are
mentioning.

Let me know if I can try anything else to help.

Cheers,

David.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/kgori/sigfit/issues/50?email_source=notifications&email_token=ACNYRHEGOUPSK7ESE5EDBWDQSUYZ5A5CNFSM4JJXU332YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEDPONUA#issuecomment-551478992>,
or unsubscribe

**Comment by baezortega** [comment]
Hi David,

The new version of the package is already out on GitHub:
https://github.com/kgori/sigfit.

The installation command has changed; I would recommend you to uninstall
the version you have before installing the new one. Because the new version
of Stan depends on C++14 rather than C++11, you might run into some issues.
Let me know how it works.

Best,
Adrian

**Comment by Dagsbio** [comment]
Thank you! will try right now

**Comment by Dagsbio** [comment]
Yes, now working perfectly :)
