### ISSUE TITLE
Preparing mutational opportunities matrix?

### ISSUE THREAD

**Issue by kmegq** [kgori/sigfit#56]
Dear Kevin,

Would you be able to provide any additional guidance on preparing the opportunity matrix from a non-human genome for use in the convert_signatures() function? I would like to prepare an opportunity matrix from the canine genome, CanFam3 build in order to fit known COSMIC signatures to canine samples.

Is the matrix a list of total counts of trinucleotides in the genome of interest, or the fraction of trinucleotides in the genome over the total number of trinucleotides? Are there tools that you recommend for extracting this information, and would you be able to provide an example file?

Also, are the human-genome and human-exome parameters hg19 or hg38?

Thank you for your help!

Best,
Kate

**Comment by baezortega** [comment]
Hi Kate,

The opportunities can be the trinucleotide frequencies over the genome of interest, but they need to be given as a matrix with one row per sample and one column per mutation type.

I'm attaching an RData object containing the vector of trinucleotide frequencies for the entire CanFam3.1 genome, as a 96-element vector called `trinuc.freqs.canfam3`: [trinuc_freqs_canfam3.1.RData.zip](https://github.com/kgori/sigfit/files/6404547/trinuc_freqs_canfam3.1.RData.zip).

You can also extract them yourself using the `trinucleotideFrequency` function in the Biostrings package, but you would need to collapse (merge) every complementary pair of trinucleotides (e.g. AAA and TTT) so that you only have 32 pyrimidine trinucleotides (with C/T as the middle base), and then arrange them into a 96-element vector following order of trinucleotides in the mutational spectrum.

So, if your number of samples is `nsamples`, you can built the opportunities matrix as:

`opps <- matrix(rep(trinuc.freqs.canfam3, nsamples), nrow = nsamples, byrow = TRUE)`

And then you can provide this matrix to the signature fitting function using the `opportunities` argument.
Before fitting the COSMIC signatures, you will also have to transform them using:

`cosmic.normalised <- convert_signatures(cosmic_signatures_v3, opportunities_from="human-genome")`

This essentially divides each signature by the human genome (hg19) trinucleotide frequencies, making them genome-independent.

I hope this helps, please let me know otherwise.

Best,
Adrian

**Comment by kmegq** [comment]
Dear Adrian, 

Thank you so much for providing the mutational opportunities for CanFam3, that was incredibly helpful!
I have been working with the data to be sure that I understand everything. I will also check out the BioStrings package, as I will need to make several custom intervals, as well.

For the normalization of the cosmic signatures, under what circumstances is it recommended that I normalize as you suggested above so that they are "genome-independent?" Should I always use them that way, or are there cases where it would be better to convert them to the CanFam3 opportunities if we are using them with canine data? I noticed that which signature is selected by the `match_signatures` function changes sometimes depending on which normalization I choose.

Thank you again for all your help!

Best,
Kate

**Comment by baezortega** [comment]
Hi Kate,

If you are using the COSMIC signatures, I think it doesn't make a difference whether you transform the signatures from human to CanFam3 beforehand (providing no opportunities to the model), or you make the signatures genome-independent and provide the CanFam3 opportunities to the signature fitting model (as in my previous message). That is, applying the CanFam3 opportunities to the signatures is the same as inputting them to the model while using genome-independent signatures.

However, I recently discovered a problem with `convert_signatures` that happens if you provide the opportunities as a vector instead of as a matrix (we just fixed this problem in a new release). To avoid this problem, when using `convert_signatures` your `opportunities_to` should be a matrix like the `opps` matrix in my example above, with the difference that the number of rows should be equal to the number of signatures.

When you say that the signature selected by `match_signatures` changes depending on the normalisation, what are you matching against the COSMIC signatures? Did you extract you own signatures from your samples?

Best,
Adrian
